package encoder

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

type outputArgsCase struct {
	Kind string `json:"kind"`
	Comp struct {
		FPS         int     `json:"fps"`
		GopSeconds  float64 `json:"gopSeconds"`
		BitrateKbps int     `json:"bitrateKbps"`
		MaxrateKbps int     `json:"maxrateKbps"`
		BufsizeKbps int     `json:"bufsizeKbps"`
		Preset      string  `json:"preset"`
		Threads     int     `json:"threads"`
	} `json:"comp"`
	Args []string `json:"args"`
}

// TestOutputArgsMatchesTheNodeImplementation proves the Go port matches
// server/src/encoder.js's outputArgs() exactly, not just itself — the
// fixture was generated by calling the real Node module on the dev box.
func TestOutputArgsMatchesTheNodeImplementation(t *testing.T) {
	data, err := os.ReadFile("testdata/output_args_cases.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []outputArgsCase
	if err := json.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	if len(cases) == 0 {
		t.Fatal("no cases loaded")
	}

	for i, c := range cases {
		comp := Composition{
			FPS: c.Comp.FPS, GopSeconds: c.Comp.GopSeconds, BitrateKbps: c.Comp.BitrateKbps,
			MaxrateKbps: c.Comp.MaxrateKbps, BufsizeKbps: c.Comp.BufsizeKbps,
			Preset: c.Comp.Preset, Threads: c.Comp.Threads,
		}
		got := OutputArgs(c.Kind, comp)
		if strings.Join(got, " ") != strings.Join(c.Args, " ") {
			t.Errorf("case %d (kind=%s): got %v, want %v", i, c.Kind, got, c.Args)
		}
	}
}

func TestResolvePrefersHardwareInAutoMode(t *testing.T) {
	c := New("ffmpeg", "/dev/dri/renderD128", "")
	c.Encoders["libx264"] = true
	c.Encoders["h264_vaapi"] = true
	c.VAAPIDevice = true
	c.Functional["vaapi"] = FunctionalResult{OK: true}

	if got := c.Resolve("auto"); got != "vaapi" {
		t.Errorf("Resolve(auto) = %q, want vaapi", got)
	}
}

func TestResolveFallsBackToX264WhenRequestedIsUnavailable(t *testing.T) {
	c := New("ffmpeg", "/dev/dri/renderD128", "")
	c.Encoders["libx264"] = true

	if got := c.Resolve("nvenc"); got != "x264" {
		t.Errorf("Resolve(nvenc) with no NVENC = %q, want x264", got)
	}
}

func TestResolveHonorsAnExplicitUsableRequest(t *testing.T) {
	c := New("ffmpeg", "/dev/dri/renderD128", "")
	c.Encoders["libx264"] = true
	c.Encoders["h264_qsv"] = true
	c.VAAPIDevice = true
	c.Functional["qsv"] = FunctionalResult{OK: true}

	if got := c.Resolve("qsv"); got != "qsv" {
		t.Errorf("Resolve(qsv) = %q, want qsv", got)
	}
}

func TestAvailableReportsWhyAnEncoderIsUnusable(t *testing.T) {
	c := New("ffmpeg", "/dev/dri/renderD128", "")
	c.Encoders["libx264"] = true
	c.Encoders["h264_vaapi"] = true
	c.VAAPIDevice = false // built into ffmpeg, but no device node

	for _, e := range c.Available() {
		if e.ID == "vaapi" {
			if e.Usable {
				t.Fatal("vaapi should not be usable with no device present")
			}
			if e.Reason == "" {
				t.Error("an unusable encoder must explain why")
			}
		}
	}
}
